# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pqt5_add_icon.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 593)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/ice_cream/ice_cream.ico"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_ice_cream_count = QtWidgets.QLabel(self.centralwidget)
        self.label_ice_cream_count.setGeometry(QtCore.QRect(350, 270, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_ice_cream_count.setFont(font)
        self.label_ice_cream_count.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ice_cream_count.setObjectName("label_ice_cream_count")
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(210, 120, 171, 101))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/add/add.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.pushButton_add.setIcon(icon1)
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_remove = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_remove.setGeometry(QtCore.QRect(430, 120, 171, 101))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(":/remove/minus.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.pushButton_remove.setIcon(icon2)
        self.pushButton_remove.setObjectName("pushButton_remove")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_ice_cream_count.setText(_translate("MainWindow", "0"))
        self.pushButton_add.setText(_translate("MainWindow", "Add"))
        self.pushButton_remove.setText(_translate("MainWindow", "Remove"))


import icons_rc


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
