# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\table_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1056, 640)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(60, 70, 661, 461))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 30, 161, 16))
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(800, 80, 160, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_add_row = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_add_row.setObjectName("pushButton_add_row")
        self.verticalLayout.addWidget(self.pushButton_add_row)
        self.pushButton_delete_row = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_delete_row.setObjectName("pushButton_delete_row")
        self.verticalLayout.addWidget(self.pushButton_delete_row)
        self.pushButton_add_column = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_add_column.setObjectName("pushButton_add_column")
        self.verticalLayout.addWidget(self.pushButton_add_column)
        self.pushButton_delete_column = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_delete_column.setObjectName("pushButton_delete_column")
        self.verticalLayout.addWidget(self.pushButton_delete_column)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Surname"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Phone"))
        self.label.setText(_translate("Form", "User Registeries"))
        self.pushButton_add_row.setText(_translate("Form", "Satir Ekle"))
        self.pushButton_delete_row.setText(_translate("Form", "Satir Sil"))
        self.pushButton_add_column.setText(_translate("Form", "Column Ekle"))
        self.pushButton_delete_column.setText(_translate("Form", "Column Sil"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
