# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\radio_usage_pyqt5.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(495, 414)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(200, 320, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_menu_sizes = QtWidgets.QGroupBox(Form)
        self.groupBox_menu_sizes.setGeometry(QtCore.QRect(50, 70, 181, 181))
        self.groupBox_menu_sizes.setObjectName("groupBox_menu_sizes")
        self.radioButton_small_meal = QtWidgets.QRadioButton(self.groupBox_menu_sizes)
        self.radioButton_small_meal.setGeometry(QtCore.QRect(20, 30, 95, 20))
        self.radioButton_small_meal.setObjectName("radioButton_small_meal")
        self.radioButton_medium_meal = QtWidgets.QRadioButton(self.groupBox_menu_sizes)
        self.radioButton_medium_meal.setGeometry(QtCore.QRect(20, 60, 95, 20))
        self.radioButton_medium_meal.setObjectName("radioButton_medium_meal")
        self.radioButton_large_meal = QtWidgets.QRadioButton(self.groupBox_menu_sizes)
        self.radioButton_large_meal.setGeometry(QtCore.QRect(20, 90, 95, 20))
        self.radioButton_large_meal.setObjectName("radioButton_large_meal")
        self.radioButton_double_meal = QtWidgets.QRadioButton(self.groupBox_menu_sizes)
        self.radioButton_double_meal.setGeometry(QtCore.QRect(20, 130, 95, 20))
        self.radioButton_double_meal.setObjectName("radioButton_double_meal")
        self.groupBox_beverage_options = QtWidgets.QGroupBox(Form)
        self.groupBox_beverage_options.setGeometry(QtCore.QRect(270, 70, 161, 181))
        self.groupBox_beverage_options.setObjectName("groupBox_beverage_options")
        self.radioButton_ayran = QtWidgets.QRadioButton(self.groupBox_beverage_options)
        self.radioButton_ayran.setGeometry(QtCore.QRect(10, 30, 95, 20))
        self.radioButton_ayran.setObjectName("radioButton_ayran")
        self.radioButton_cola = QtWidgets.QRadioButton(self.groupBox_beverage_options)
        self.radioButton_cola.setGeometry(QtCore.QRect(10, 60, 95, 20))
        self.radioButton_cola.setObjectName("radioButton_cola")
        self.radioButton_ice_tea = QtWidgets.QRadioButton(self.groupBox_beverage_options)
        self.radioButton_ice_tea.setGeometry(QtCore.QRect(10, 90, 95, 20))
        self.radioButton_ice_tea.setObjectName("radioButton_ice_tea")
        self.radioButton_mineral_water = QtWidgets.QRadioButton(self.groupBox_beverage_options)
        self.radioButton_mineral_water.setGeometry(QtCore.QRect(10, 130, 131, 20))
        self.radioButton_mineral_water.setObjectName("radioButton_mineral_water")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Radio Kullanimi"))
        self.pushButton.setText(_translate("Form", "Pay"))
        self.groupBox_menu_sizes.setTitle(_translate("Form", "Menu Options"))
        self.radioButton_small_meal.setText(_translate("Form", "Small"))
        self.radioButton_medium_meal.setText(_translate("Form", "Medium"))
        self.radioButton_large_meal.setText(_translate("Form", "Large"))
        self.radioButton_double_meal.setText(_translate("Form", "Double"))
        self.groupBox_beverage_options.setTitle(_translate("Form", "Beverage Options"))
        self.radioButton_ayran.setText(_translate("Form", "Ayran"))
        self.radioButton_cola.setText(_translate("Form", "Cola"))
        self.radioButton_ice_tea.setText(_translate("Form", "Ice Tea"))
        self.radioButton_mineral_water.setText(_translate("Form", "Mineral Water"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
